site_name: REDCap Documentation
site_url: https://bmb-nord.github.io/redcap

theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

      features:
        - search.highlight
        - search.share
        - navigation.footer

  font:
    text: Open Sans
    code: Fira Code

  icon:
    logo: fontawesome/solid/book-open-reader


nav:

  - Welcome: index.md

  - User:
    - New user: User/new-user.md
    - User Rights: access-rights.md

  - Instruments: 
    - Introduction: instrument.md
    - Fields: fields.md

  - Surveys:
    - Introduction: surveys-inroduction.md

  - Multi-Language: 
    - Setup: Multi-Language/setup-german.md

  - External Module:
    - Cross-Project Piping: cross-project-piping.md
    - Instance Table: instance-table.md
    - JavaScript Injector: javascript-sector.md

  - API:
    - Setup: API/api.md
    - Postman: API/postman.md 

  - Contribution: 
    - Contributing: CONTRIBUTION.md
    - Code of Conduct: CODE_OF_CONDUCT.md
    - Developer Guide: DEVELOPER.md


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

plugins:
  - glightbox
  - search