site_name: REDCap Documentation
site_url: https://bmb-nord.github.io/redcap

theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

      features:
        - search.highlight
        - search.share
        - navigation.footer

  font:
    text: Merriweather Sans
    code: Red Hat Mono

  icon:
    logo: fontawesome/solid/book-open-reader


# Emoji Pack of MkDocs
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:

  - Welcome: index.md

  - Access Rights: access-rights.md

  - Instruments: instrument.md

  - Surveys: surveys.md

  - Multi-Language: 
    - Setup: Multi-Language/setup-german.md

  - External Module:
    - Cross-Project Piping: cross-project-piping.md
    - Instance Table: instance-table.md
    - JavaScript Injector: javascript-sector.md

  - API: api.md

  - Contribution: CONTRIBUTION.md

# extra:
#   social:
#     - icon: simple/linkedin
#       link: https://linkedin.com/in/willettjames


# copyright: Copyright &copy; 2025 BMB Nord